version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: doctorapp
      POSTGRES_USER: doctorapp
      POSTGRES_PASSWORD: doctorapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend         # 👈 build inside backend folder
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend        # 👈 build inside frontend folder
      dockerfile: Dockerfile
    env_file:
      - frontend/.env.local
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db-data:
